-- Drop all tables
DROP TABLE IF EXISTS Customer;
DROP TABLE IF EXISTS OrderProduct;
DROP TABLE IF EXISTS OrderEntry;
DROP TABLE IF EXISTS [Order];
DROP TABLE IF EXISTS ProductDiscountProduct;
DROP TABLE IF EXISTS DiscountFreeProduct;
DROP TABLE IF EXISTS Discount;
DROP TABLE IF EXISTS CartEntry;
DROP TABLE IF EXISTS Cart;
DROP TABLE IF EXISTS Product;
DROP TABLE IF EXISTS Shop;